apiVersion: v1
kind: Service
metadata:
  name: url-fetcher-service # Service 的名称保持不变
spec:
  type: ClusterIP
  selector:
    app: url-fetcher # 这个标签选择器保持不变，指向你的 Deployment Pods
  ports:
    - protocol: TCP
      port: 80 # Service 在集群内部监听的端口，供 Traefik 访问
      targetPort: 5000 # 流量最终转发到容器的 5000 端口